// source: vault.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.vault.v1.AuthenticateEntityRequest', null, global);
goog.exportSymbol('proto.vault.v1.AuthenticateEntityResponse', null, global);
goog.exportSymbol('proto.vault.v1.CreateEntityRequest', null, global);
goog.exportSymbol('proto.vault.v1.CreateEntityResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vault.v1.CreateEntityRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vault.v1.CreateEntityRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vault.v1.CreateEntityRequest.displayName = 'proto.vault.v1.CreateEntityRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vault.v1.CreateEntityResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vault.v1.CreateEntityResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vault.v1.CreateEntityResponse.displayName = 'proto.vault.v1.CreateEntityResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vault.v1.AuthenticateEntityRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vault.v1.AuthenticateEntityRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vault.v1.AuthenticateEntityRequest.displayName = 'proto.vault.v1.AuthenticateEntityRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vault.v1.AuthenticateEntityResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vault.v1.AuthenticateEntityResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vault.v1.AuthenticateEntityResponse.displayName = 'proto.vault.v1.AuthenticateEntityResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vault.v1.CreateEntityRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.vault.v1.CreateEntityRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vault.v1.CreateEntityRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vault.v1.CreateEntityRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    countryCode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    phoneNumber: jspb.Message.getFieldWithDefault(msg, 2, ""),
    password: jspb.Message.getFieldWithDefault(msg, 3, ""),
    clientPublishPubKey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    clientDeviceIdPubKey: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ownershipProofResponse: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vault.v1.CreateEntityRequest}
 */
proto.vault.v1.CreateEntityRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vault.v1.CreateEntityRequest;
  return proto.vault.v1.CreateEntityRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vault.v1.CreateEntityRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vault.v1.CreateEntityRequest}
 */
proto.vault.v1.CreateEntityRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountryCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoneNumber(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientPublishPubKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientDeviceIdPubKey(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnershipProofResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vault.v1.CreateEntityRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vault.v1.CreateEntityRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vault.v1.CreateEntityRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vault.v1.CreateEntityRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCountryCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPhoneNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getClientPublishPubKey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getClientDeviceIdPubKey();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getOwnershipProofResponse();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string country_code = 1;
 * @return {string}
 */
proto.vault.v1.CreateEntityRequest.prototype.getCountryCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityRequest} returns this
 */
proto.vault.v1.CreateEntityRequest.prototype.setCountryCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string phone_number = 2;
 * @return {string}
 */
proto.vault.v1.CreateEntityRequest.prototype.getPhoneNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityRequest} returns this
 */
proto.vault.v1.CreateEntityRequest.prototype.setPhoneNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.vault.v1.CreateEntityRequest.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityRequest} returns this
 */
proto.vault.v1.CreateEntityRequest.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string client_publish_pub_key = 4;
 * @return {string}
 */
proto.vault.v1.CreateEntityRequest.prototype.getClientPublishPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityRequest} returns this
 */
proto.vault.v1.CreateEntityRequest.prototype.setClientPublishPubKey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string client_device_id_pub_key = 5;
 * @return {string}
 */
proto.vault.v1.CreateEntityRequest.prototype.getClientDeviceIdPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityRequest} returns this
 */
proto.vault.v1.CreateEntityRequest.prototype.setClientDeviceIdPubKey = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string ownership_proof_response = 6;
 * @return {string}
 */
proto.vault.v1.CreateEntityRequest.prototype.getOwnershipProofResponse = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityRequest} returns this
 */
proto.vault.v1.CreateEntityRequest.prototype.setOwnershipProofResponse = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vault.v1.CreateEntityResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.vault.v1.CreateEntityResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vault.v1.CreateEntityResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vault.v1.CreateEntityResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    requiresOwnershipProof: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    longLivedToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    serverPublishPubKey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    serverDeviceIdPubKey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    message: jspb.Message.getFieldWithDefault(msg, 5, ""),
    nextAttemptTimestamp: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vault.v1.CreateEntityResponse}
 */
proto.vault.v1.CreateEntityResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vault.v1.CreateEntityResponse;
  return proto.vault.v1.CreateEntityResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vault.v1.CreateEntityResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vault.v1.CreateEntityResponse}
 */
proto.vault.v1.CreateEntityResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRequiresOwnershipProof(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLongLivedToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerPublishPubKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerDeviceIdPubKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNextAttemptTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vault.v1.CreateEntityResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vault.v1.CreateEntityResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vault.v1.CreateEntityResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vault.v1.CreateEntityResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequiresOwnershipProof();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getLongLivedToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getServerPublishPubKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getServerDeviceIdPubKey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getNextAttemptTimestamp();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional bool requires_ownership_proof = 1;
 * @return {boolean}
 */
proto.vault.v1.CreateEntityResponse.prototype.getRequiresOwnershipProof = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vault.v1.CreateEntityResponse} returns this
 */
proto.vault.v1.CreateEntityResponse.prototype.setRequiresOwnershipProof = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string long_lived_token = 2;
 * @return {string}
 */
proto.vault.v1.CreateEntityResponse.prototype.getLongLivedToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityResponse} returns this
 */
proto.vault.v1.CreateEntityResponse.prototype.setLongLivedToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string server_publish_pub_key = 3;
 * @return {string}
 */
proto.vault.v1.CreateEntityResponse.prototype.getServerPublishPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityResponse} returns this
 */
proto.vault.v1.CreateEntityResponse.prototype.setServerPublishPubKey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string server_device_id_pub_key = 4;
 * @return {string}
 */
proto.vault.v1.CreateEntityResponse.prototype.getServerDeviceIdPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityResponse} returns this
 */
proto.vault.v1.CreateEntityResponse.prototype.setServerDeviceIdPubKey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string message = 5;
 * @return {string}
 */
proto.vault.v1.CreateEntityResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.CreateEntityResponse} returns this
 */
proto.vault.v1.CreateEntityResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 next_attempt_timestamp = 6;
 * @return {number}
 */
proto.vault.v1.CreateEntityResponse.prototype.getNextAttemptTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.vault.v1.CreateEntityResponse} returns this
 */
proto.vault.v1.CreateEntityResponse.prototype.setNextAttemptTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.vault.v1.AuthenticateEntityRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vault.v1.AuthenticateEntityRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vault.v1.AuthenticateEntityRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    phoneNumber: jspb.Message.getFieldWithDefault(msg, 1, ""),
    password: jspb.Message.getFieldWithDefault(msg, 2, ""),
    clientPublishPubKey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    clientDeviceIdPubKey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    ownershipProofResponse: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vault.v1.AuthenticateEntityRequest}
 */
proto.vault.v1.AuthenticateEntityRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vault.v1.AuthenticateEntityRequest;
  return proto.vault.v1.AuthenticateEntityRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vault.v1.AuthenticateEntityRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vault.v1.AuthenticateEntityRequest}
 */
proto.vault.v1.AuthenticateEntityRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoneNumber(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientPublishPubKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientDeviceIdPubKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnershipProofResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vault.v1.AuthenticateEntityRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vault.v1.AuthenticateEntityRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vault.v1.AuthenticateEntityRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPhoneNumber();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getClientPublishPubKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getClientDeviceIdPubKey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getOwnershipProofResponse();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string phone_number = 1;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.getPhoneNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityRequest} returns this
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.setPhoneNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityRequest} returns this
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string client_publish_pub_key = 3;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.getClientPublishPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityRequest} returns this
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.setClientPublishPubKey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string client_device_id_pub_key = 4;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.getClientDeviceIdPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityRequest} returns this
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.setClientDeviceIdPubKey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string ownership_proof_response = 5;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.getOwnershipProofResponse = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityRequest} returns this
 */
proto.vault.v1.AuthenticateEntityRequest.prototype.setOwnershipProofResponse = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.vault.v1.AuthenticateEntityResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vault.v1.AuthenticateEntityResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vault.v1.AuthenticateEntityResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    requiresOwnershipProof: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    longLivedToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    serverPublishPubKey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    serverDeviceIdPubKey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    message: jspb.Message.getFieldWithDefault(msg, 5, ""),
    nextAttemptTimestamp: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vault.v1.AuthenticateEntityResponse}
 */
proto.vault.v1.AuthenticateEntityResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vault.v1.AuthenticateEntityResponse;
  return proto.vault.v1.AuthenticateEntityResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vault.v1.AuthenticateEntityResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vault.v1.AuthenticateEntityResponse}
 */
proto.vault.v1.AuthenticateEntityResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRequiresOwnershipProof(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLongLivedToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerPublishPubKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerDeviceIdPubKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNextAttemptTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vault.v1.AuthenticateEntityResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vault.v1.AuthenticateEntityResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vault.v1.AuthenticateEntityResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequiresOwnershipProof();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getLongLivedToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getServerPublishPubKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getServerDeviceIdPubKey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getNextAttemptTimestamp();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional bool requires_ownership_proof = 1;
 * @return {boolean}
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.getRequiresOwnershipProof = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vault.v1.AuthenticateEntityResponse} returns this
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.setRequiresOwnershipProof = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string long_lived_token = 2;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.getLongLivedToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityResponse} returns this
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.setLongLivedToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string server_publish_pub_key = 3;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.getServerPublishPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityResponse} returns this
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.setServerPublishPubKey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string server_device_id_pub_key = 4;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.getServerDeviceIdPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityResponse} returns this
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.setServerDeviceIdPubKey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string message = 5;
 * @return {string}
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vault.v1.AuthenticateEntityResponse} returns this
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 next_attempt_timestamp = 6;
 * @return {number}
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.getNextAttemptTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.vault.v1.AuthenticateEntityResponse} returns this
 */
proto.vault.v1.AuthenticateEntityResponse.prototype.setNextAttemptTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


goog.object.extend(exports, proto.vault.v1);
